docker start redis2
docker start neo4j2
docker start mongo2
docker start postgres2
docker start elastic2
docker start pgadmin2
docker start magical_jonson
docker start mongo-express2
docker start api
docker start ui