docker stop redis2
docker stop neo4j2
docker stop mongo2
docker stop postgres2
docker stop elastic2
docker stop pgadmin2
docker stop 6ba
docker stop mongo-express2
docker stop api
docker stop ui